using Microsoft.EntityFrameworkCore;
namespace AceriaData.ConsoleApp;
public class OrdenFabricacion { public int Id{get;set;} public string NumeroOrden{get;set;}=string.Empty; public string Cliente{get;set;}=string.Empty; public DateTime FechaCreacion{get;set;} public List<PlanchaAcero> Planchas{get;set;}=new(); }
public class PlanchaAcero { public int Id{get;set;} public int OrdenId{get;set;} public double Espesor{get;set;} public double Ancho{get;set;} public double Largo{get;set;} public OrdenFabricacion Orden{get;set;}=null!; }
public class Aleacion { public int Id{get;set;} public string Nombre{get;set;}=string.Empty; public double PorcentajeCarbono{get;set;} public double PorcentajeManganeso{get;set;} }
public class EstadoOrden { public int Id{get;set;} public string Nombre{get;set;}=string.Empty; public string Descripcion{get;set;}=string.Empty; }
public class AceriaDbContext:DbContext { public DbSet<OrdenFabricacion> OrdenesFabricacion=>Set<OrdenFabricacion>(); public DbSet<PlanchaAcero> PlanchasAcero=>Set<PlanchaAcero>(); public DbSet<Aleacion> Aleaciones=>Set<Aleacion>(); public DbSet<EstadoOrden> EstadosOrden=>Set<EstadoOrden>(); protected override void OnConfiguring(DbContextOptionsBuilder b)=>b.UseSqlServer("Server=(localdb)\\MSSQLLocalDB;Database=AceriaDB_CP06;Trusted_Connection=True;TrustServerCertificate=True;"); }
public static class AceriaDbContextFactory { public static AceriaDbContext Create()=>new(); }
public static class Program { public static void Main(){using(var c=AceriaDbContextFactory.Create()){c.Database.EnsureDeleted();c.Database.Migrate();} Insertar("OF-001","Norte");Insertar("OF-002","Sur");Actualizar("OF-002","Oeste");global::System.Console.WriteLine($"Existe: {Existe("OF-001")}; Total: {Contar()}");Eliminar("OF-001");Listar();} static void Insertar(string n,string cl){using var c=AceriaDbContextFactory.Create();c.OrdenesFabricacion.Add(new(){NumeroOrden=n,Cliente=cl,FechaCreacion=DateTime.Now});c.SaveChanges();} static void Listar(){using var c=AceriaDbContextFactory.Create();foreach(var o in c.OrdenesFabricacion.AsNoTracking().OrderBy(x=>x.Id))global::System.Console.WriteLine(o.NumeroOrden);} static bool Actualizar(string n,string cl){using var c=AceriaDbContextFactory.Create();var o=c.OrdenesFabricacion.FirstOrDefault(x=>x.NumeroOrden==n);if(o is null)return false;o.Cliente=cl;c.SaveChanges();return true;} static bool Existe(string n){using var c=AceriaDbContextFactory.Create();return c.OrdenesFabricacion.Any(x=>x.NumeroOrden==n);} static int Contar(){using var c=AceriaDbContextFactory.Create();return c.OrdenesFabricacion.Count();} static bool Eliminar(string n){using var c=AceriaDbContextFactory.Create();var o=c.OrdenesFabricacion.FirstOrDefault(x=>x.NumeroOrden==n);if(o is null)return false;c.Remove(o);c.SaveChanges();return true;} }
