using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
namespace AceriaData.ConsoleApp;
public class OrdenFabricacion{public int Id{get;set;}public string NumeroOrden{get;set;}=string.Empty;public string Cliente{get;set;}=string.Empty;public DateTime FechaCreacion{get;set;}public List<PlanchaAcero> Planchas{get;set;}=new();}
public class PlanchaAcero{public int Id{get;set;}public int OrdenId{get;set;}public double Espesor{get;set;}public double Ancho{get;set;}public double Largo{get;set;}public OrdenFabricacion Orden{get;set;}=null!;}
public class Aleacion{public int Id{get;set;}public string Nombre{get;set;}=string.Empty;public double PorcentajeCarbono{get;set;}public double PorcentajeManganeso{get;set;}}
public class EstadoOrden{public int Id{get;set;}public string Nombre{get;set;}=string.Empty;public string Descripcion{get;set;}=string.Empty;}
public class AceriaDbContext:DbContext{readonly string _cs;public AceriaDbContext(string cs)=>_cs=cs;public DbSet<OrdenFabricacion> OrdenesFabricacion=>Set<OrdenFabricacion>();public DbSet<PlanchaAcero> PlanchasAcero=>Set<PlanchaAcero>();public DbSet<Aleacion>Aleaciones=>Set<Aleacion>();public DbSet<EstadoOrden>EstadosOrden=>Set<EstadoOrden>();protected override void OnConfiguring(DbContextOptionsBuilder b){if(!b.IsConfigured)b.UseSqlServer(_cs).LogTo(global::System.Console.WriteLine,new[]{"Microsoft.EntityFrameworkCore.Database.Command"},LogLevel.Information).EnableDetailedErrors();}}
public static class Program{public static void Main(){var cfg=new ConfigurationBuilder().SetBasePath(AppContext.BaseDirectory).AddJsonFile("appsettings.json").AddEnvironmentVariables().Build();var cs=cfg.GetConnectionString("AceriaDB")!;using var c=new AceriaDbContext(cs);c.Database.EnsureDeleted();c.Database.Migrate();c.Add(new OrdenFabricacion{NumeroOrden="OF-001",Cliente="Norte",FechaCreacion=DateTime.Now});c.SaveChanges();global::System.Console.WriteLine(c.Database.ProviderName);global::System.Console.WriteLine(c.OrdenesFabricacion.Where(o=>o.Cliente=="Norte").ToQueryString());}}
