// <auto-generated />
using System;
using AceriaData.ConsoleApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AceriaData.ConsoleApp.Migrations
{
    [DbContext(typeof(AceriaDbContext))]
    partial class AceriaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AceriaData.ConsoleApp.Aleacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");


                        // ============================================================================
            // FRAGMENTO PDF M02 2.11 - PASO 10
            // BLOQUE PEDAGÓGICO ACTIVABLE DEL PDF.
            // Para probarlo: comenta temporalmente el bloque activo equivalente indicado
            // y descomenta SOLO el código comprendido entre /* y */.
            /*
                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("PorcentajeCarbono")
                        .HasColumnType("float");

                    b.Property<double>("PorcentajeManganeso")
                        .HasColumnType("float");

                    b.HasKey("Id");
            */
            // ============================================================================
                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("PorcentajeCarbono")
                        .HasColumnType("float");

                    b.Property<double>("PorcentajeManganeso")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasAlternateKey("Codigo")
                        .HasName("AK_Aleaciones_Codigo");

                    b.HasIndex("Nombre")
                        .HasDatabaseName("IX_Aleaciones_Nombre");

                    b.HasIndex("PorcentajeCarbono", "PorcentajeManganeso")
                        .HasDatabaseName("IX_Aleaciones_Porcentajes");

                    b.ToTable("Aleaciones", null, t =>
                        {
                            t.HasCheckConstraint("CK_Aleaciones_PorcentajeCarbono", "[PorcentajeCarbono] >= 0 AND [PorcentajeCarbono] <= 2");

                            t.HasCheckConstraint("CK_Aleaciones_PorcentajeManganeso", "[PorcentajeManganeso] >= 0 AND [PorcentajeManganeso] <= 5");
                        });
                });

            modelBuilder.Entity("AceriaData.ConsoleApp.CertificadoCalidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroCertificado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OrdenId")
                        .HasColumnType("int");

                    b.Property<string>("OrganismoCertificador")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasAlternateKey("NumeroCertificado")
                        .HasName("AK_CertificadosCalidad_NumeroCertificado");

                    b.HasIndex("FechaEmision")
                        .HasDatabaseName("IX_CertificadosCalidad_FechaEmision");

                    b.HasIndex("OrdenId")
                        .IsUnique();

                    b.ToTable("CertificadosCalidad", (string)null);
                });

            modelBuilder.Entity("AceriaData.ConsoleApp.DetalleOrden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ComposicionQuimica")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OrdenId")
                        .HasColumnType("int");

                    b.Property<double>("TemperaturaColada")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("OrdenId")
                        .IsUnique();

                    b.ToTable("DetallesOrden", (string)null);
                });

            modelBuilder.Entity("AceriaData.ConsoleApp.EstadoOrden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("EstadosOrden", (string)null);
                });

            modelBuilder.Entity("AceriaData.ConsoleApp.OrdenAleacion", b =>
                {
                    b.Property<int>("OrdenFabricacionId")
                        .HasColumnType("int");

                    b.Property<int>("AleacionId")
                        .HasColumnType("int");

                    b.Property<decimal>("CantidadUtilizada")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("EstadoRelacion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Activa");

                    b.Property<DateTime>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("OrdenFabricacionId", "AleacionId");

                    b.HasIndex("AleacionId")
                        .HasDatabaseName("IX_OrdenesAleaciones_AleacionId");

                    b.HasIndex("EstadoRelacion")
                        .HasDatabaseName("IX_OrdenesAleaciones_EstadoRelacion_Activas")
                        .HasFilter("[EstadoRelacion] = 'Activa'");

                    b.ToTable("OrdenesAleaciones", (string)null);
                });

            modelBuilder.Entity("AceriaData.ConsoleApp.OrdenFabricacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NumeroOrden")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasAlternateKey("NumeroOrden")
                        .HasName("AK_OrdenesFabricacion_NumeroOrden");

                    b.HasIndex("Cliente")
                        .HasDatabaseName("IX_OrdenesFabricacion_Cliente");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_OrdenesFabricacion_Estado_Incluye");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Estado"), new[] { "NumeroOrden", "Cliente", "FechaCreacion" });

                    b.HasIndex("FechaEntrega")
                        .HasDatabaseName("IX_OrdenesFabricacion_FechaEntrega_Pendientes")
                        .HasFilter("[Estado] = 'Pendiente'");

                    b.HasIndex("Cliente", "FechaCreacion")
                        .HasDatabaseName("IX_OrdenesFabricacion_Cliente_FechaCreacion");

                    b.ToTable("OrdenesFabricacion", (string)null);
                });

            modelBuilder.Entity("AceriaData.ConsoleApp.PlanchaAcero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<double>("Ancho")
                        .HasColumnType("float");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Espesor")
                        .HasColumnType("float");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double>("Largo")
                        .HasColumnType("float");

                    b.Property<int>("OrdenId")
                        .HasColumnType("int");

                    b.Property<decimal>("Peso")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("Espesor")
                        .HasDatabaseName("IX_PlanchasAcero_Espesor_Activas")
                        .HasFilter("[Activa] = 1");

                    b.HasIndex("OrdenId", "Activa")
                        .HasDatabaseName("IX_PlanchasAcero_OrdenId_Activa");

                    b.ToTable("PlanchasAcero", null, t =>
                        {
                            t.HasCheckConstraint("CK_PlanchasAcero_Ancho", "[Ancho] > 0");

                            t.HasCheckConstraint("CK_PlanchasAcero_Espesor", "[Espesor] > 0");

                            t.HasCheckConstraint("CK_PlanchasAcero_Largo", "[Largo] > 0");

                            t.HasCheckConstraint("CK_PlanchasAcero_Peso", "[Peso] > 0");
                        });
                });

            modelBuilder.Entity("AceriaData.ConsoleApp.CertificadoCalidad", b =>
                {
                    b.HasOne("AceriaData.ConsoleApp.OrdenFabricacion", "Orden")
                        .WithOne("Certificado")
                        .HasForeignKey("AceriaData.ConsoleApp.CertificadoCalidad", "OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("AceriaData.ConsoleApp.DetalleOrden", b =>
                {
                    b.HasOne("AceriaData.ConsoleApp.OrdenFabricacion", "Orden")
                        .WithOne("Detalle")
                        .HasForeignKey("AceriaData.ConsoleApp.DetalleOrden", "OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("AceriaData.ConsoleApp.OrdenAleacion", b =>
                {
                    b.HasOne("AceriaData.ConsoleApp.Aleacion", "Aleacion")
                        .WithMany("OrdenesAleaciones")
                        .HasForeignKey("AleacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AceriaData.ConsoleApp.OrdenFabricacion", "Orden")
                        .WithMany("OrdenesAleaciones")
                        .HasForeignKey("OrdenFabricacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aleacion");

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("AceriaData.ConsoleApp.PlanchaAcero", b =>
                {
                    b.HasOne("AceriaData.ConsoleApp.OrdenFabricacion", "Orden")
                        .WithMany("Planchas")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("AceriaData.ConsoleApp.Aleacion", b =>
                {
                    b.Navigation("OrdenesAleaciones");
                });

            modelBuilder.Entity("AceriaData.ConsoleApp.OrdenFabricacion", b =>
                {
                    b.Navigation("Certificado");

                    b.Navigation("Detalle");

                    b.Navigation("OrdenesAleaciones");

                    b.Navigation("Planchas");
                });
#pragma warning restore 612, 618
        }
    }
}
