using Microsoft.EntityFrameworkCore;
namespace AceriaData.ConsoleApp;
public class OrdenFabricacion { public int Id{get;set;} public string NumeroOrden{get;set;}=string.Empty; public string Cliente{get;set;}=string.Empty; public DateTime FechaCreacion{get;set;} public List<PlanchaAcero> Planchas{get;set;}=new(); }
public class PlanchaAcero { public int Id{get;set;} public int OrdenId{get;set;} public double Espesor{get;set;} public double Ancho{get;set;} public double Largo{get;set;} public OrdenFabricacion Orden{get;set;}=null!; }
public class Aleacion { public int Id{get;set;} public string Nombre{get;set;}=string.Empty; public double PorcentajeCarbono{get;set;} public double PorcentajeManganeso{get;set;} }
public class EstadoOrden { public int Id{get;set;} public string Nombre{get;set;}=string.Empty; public string Descripcion{get;set;}=string.Empty; }
public class AceriaDbContext:DbContext { public DbSet<OrdenFabricacion> OrdenesFabricacion=>Set<OrdenFabricacion>(); public DbSet<PlanchaAcero> PlanchasAcero=>Set<PlanchaAcero>(); public DbSet<Aleacion> Aleaciones=>Set<Aleacion>(); public DbSet<EstadoOrden> EstadosOrden=>Set<EstadoOrden>(); protected override void OnConfiguring(DbContextOptionsBuilder b)=>b.UseSqlServer("Server=(localdb)\\MSSQLLocalDB;Database=AceriaDB_CP07;Trusted_Connection=True;TrustServerCertificate=True;"); }
public static class AceriaDbContextFactory { public static AceriaDbContext Create()=>new(); }
public static class Program { public static void Main(){using var c=AceriaDbContextFactory.Create();c.Database.EnsureDeleted();c.Database.Migrate();var o=new OrdenFabricacion{NumeroOrden="OF-001",Cliente="Norte",FechaCreacion=DateTime.Now};global::System.Console.WriteLine(c.Entry(o).State);c.Add(o);global::System.Console.WriteLine(c.Entry(o).State);c.SaveChanges();o.Cliente="Oeste";c.ChangeTracker.DetectChanges();global::System.Console.WriteLine($"{c.Entry(o).State} | original={c.Entry(o).OriginalValues[nameof(OrdenFabricacion.Cliente)]} | actual={o.Cliente}");c.ChangeTracker.Clear();global::System.Console.WriteLine(c.Entry(o).State);} }
